name: Prepare Hardware for CI run
description: |
  This workflow restores a stable BMFW and CMFW image to the hardware before
  executing CI jobs. It is intended to be used as a reusable (composite) step
  in other workflows, and must be run on a self-hosted runner that
  includes the stable firmware images

inputs:
  board:
    description: 'Board name (e.g., p100, p100a)'
    required: true
  version:
    description: 'Firmware version (e.g., 80.15.0.0)'
    required: true

runs:
  using: composite
  steps:
    - name: Restore stable bmfw
      working-directory: ${{ inputs.app-path }}
      shell: bash
      run: |
        # Restore stable BMFW
        /opt/tenstorrent/bin/flash-bmfw.sh ${{ inputs.board }} ${{ inputs.version }}
        # Restore stable CMFW
        tt-flash --fw-tar \
          /opt/tenstorrent/fw/stable/${{ inputs.board }}/${{ inputs.version }}.fwbundle \
          --force
