# Copyright (c) 2024 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: cfriedt
      url-base: https://github.com/cfriedt
    - name: tenstorrent
      url-base: https://github.com/tenstorrent

  # zephyr-keep-sorted-start re(^\s+\- name:)
  projects:
    - name: librpmi
      remote: cfriedt
      path: modules/lib/librpmi
      revision: 23e94f7007731e91be4de7c1d9c8c48b2173f6a2
    - name: zephyr
      remote: tenstorrent
      repo-path: zephyr-fork
      revision: 01cee78c8305362729c1293714d1ac449203152f
      import:
        name-allowlist:
          - cmsis_6
          - hal_stm32
          - mbedtls
          - mcuboot
          - nanopb
          - segger
  # zephyr-keep-sorted-stop

  group-filter:
    - +optional
