# Copyright (c) 2024 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: cfriedt
      url-base: https://github.com/cfriedt
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  # zephyr-keep-sorted-start re(^\s+\- name:)
  projects:
    - name: librpmi
      remote: cfriedt
      path: modules/lib/librpmi
      revision: 8e36df098b5114201b5d7808ed8ffd056d9fe3a0
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.2.0-rc3
      import:
        name-allowlist:
          - cmsis_6
          - hal_stm32
          - mbedtls
          - mcuboot
          - nanopb
          - segger
  # zephyr-keep-sorted-stop

  group-filter:
    - +optional
