/*
 * Copyright (c) 2024 Tenstorrent AI ULC
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef TENSTORRENT_JTAG_BOOTROM_BH_REG_DEF_H_
#define TENSTORRENT_JTAG_BOOTROM_BH_REG_DEF_H_

#define ROM_MEMORY_MEM_BASE_ADDR                0x80000000
#define RESET_UNIT_REFCLK_CNT_LO_REG_ADDR       0x800300E0
#define RESET_UNIT_ARC_MISC_CNTL_REG_ADDR       0x80030100
#define RESET_UNIT_GPIO_PAD_TRIEN_CNTL_REG_ADDR 0x800301A0

#endif
