# Copyright (c) 2024 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

if(CONFIG_SOC_TT_BLACKHOLE_DMC)
  board_runner_args(openocd "--config=${BOARD_DIR}/support/tt_blackhole_dmc.cfg")
endif()

if(CONFIG_SOC_TT_BLACKHOLE_SMC)
  board_runner_args(openocd "--config=${BOARD_DIR}/support/tt_blackhole_smc.cfg" "--use-elf" "--verify")
endif()

if(CONFIG_ARM)
  board_runner_args(stm32cubeprogrammer "--port=swd" "--reset-mode=hw")
endif()

if(CONFIG_TT_SRST_ASSIST)
  set(DMC_VARS "# Autogenerated file with variables to reset SMC. Don't edit!\n")
  string(APPEND DMC_VARS "set OPENOCD ${OPENOCD}\n")
  string(APPEND DMC_VARS "set OPENOCD_DEFAULT_PATH ${OPENOCD_DEFAULT_PATH}\n")
  string(APPEND DMC_VARS "set DMC_CFG ${CMAKE_CURRENT_LIST_DIR}/support/tt_blackhole_dmc.cfg\n")
  string(APPEND DMC_VARS "set RST_GPIO_REG ${CONFIG_TT_SRST_ASSIST_ADDR}\n")
  string(APPEND DMC_VARS "set RST_GPIO_SET_MASK ${CONFIG_TT_SRST_ASSIST_SET}\n")
  string(APPEND DMC_VARS "set RST_GPIO_CLR_MASK ${CONFIG_TT_SRST_ASSIST_CLR}\n")
  string(APPEND DMC_VARS "set RST_GPIO_SHIFT 0\n")

  if(CONFIG_BOARD_REVISION_P300A OR CONFIG_BOARD_REVISION_P300B OR CONFIG_BOARD_REVISION_P300C)
    # Add custom command to select ASIC for debug
    # PD13 is the GPIO for ARC JTAG mux. Set to connect to left chip
    string(APPEND DMC_VARS "\nproc select_asic {idx} {\n")
    string(APPEND DMC_VARS "\tglobal OPENOCD\n")
    string(APPEND DMC_VARS "\tglobal OPENOCD_DEFAULT_PATH\n")
    string(APPEND DMC_VARS "\tglobal DMC_CFG\n")
    string(APPEND DMC_VARS "\tglobal RST_GPIO_SHIFT\n")
    string(APPEND DMC_VARS "\tset JTAG_GPIO_REG 0x50000C18\n")
    string(APPEND DMC_VARS "\tset JTAG_GPIO_SET_MASK 0x2000\n")
    string(APPEND DMC_VARS "\tset JTAG_GPIO_CLR_MASK 0x20000000\n")
    string(APPEND DMC_VARS "\tset RST_GPIO_SHIFT $idx\n")
    string(APPEND DMC_VARS "\tif {$idx != 0} {\n")
    string(APPEND DMC_VARS "\t\texec $OPENOCD -s $OPENOCD_DEFAULT_PATH -f $DMC_CFG -c \"init\; mww $JTAG_GPIO_REG $JTAG_GPIO_SET_MASK\; exit\"\n")
    string(APPEND DMC_VARS "\t} else {\n")
    string(APPEND DMC_VARS "\t\texec $OPENOCD -s $OPENOCD_DEFAULT_PATH -f $DMC_CFG -c \"init\; mww $JTAG_GPIO_REG $JTAG_GPIO_CLR_MASK\; exit\"\n")
    string(APPEND DMC_VARS "\t}\n")
    string(APPEND DMC_VARS "\t# Delay for a moment. Otherwise if this function is\n")
    string(APPEND DMC_VARS "\t# called in quick succession, openocd will drop GDB connections\n")
    string(APPEND DMC_VARS "\tsleep 10\n")
    string(APPEND DMC_VARS "}\n")
    string(APPEND DMC_VARS "select_asic 0\n")
  endif()

  file(WRITE ${CMAKE_CURRENT_LIST_DIR}/support/smc-reset-vars.cfg ${DMC_VARS})
endif()

# Include debugger templates below (order is important)
include(${ZEPHYR_BASE}/boards/common/openocd.board.cmake)

if(CONFIG_ARM OR CONFIG_RISCV)
  include(${ZEPHYR_BASE}/boards/common/jlink.board.cmake)
endif()

if(CONFIG_ARM)
  include(${ZEPHYR_BASE}/boards/common/stm32cubeprogrammer.board.cmake)
endif()

board_set_flasher_ifnset(tt_flash)
board_finalize_runner_args(tt_flash)

board_set_flasher_ifnset(tt_bootstrap)
board_finalize_runner_args(tt_bootstrap --board-name ${CONFIG_BOARD_REVISION})
