/*
 * Copyright (c) 2024 Tenstorrent AI ULC
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef GDDR_PARAMS_H
#define GDDR_PARAMS_H

/* ***************************************
 *      THIS FILE IS AUTO GENERATED
 * ***************************************
 * *** DO NOT EDIT THIS FILE MANUALLY ****
 * To edit, modify
 * gddr_params.yaml and run make.
 * ***************************************
 */
#include <stdint.h>

#define GDDR_PARAMS_TABLE_T_VERSION (0x00000006)

typedef struct {
	uint32_t params_table_version;
	/* To be incremented if the fields change functionality, size or order. */
	uint32_t dram_speed;
	/* 12000, 14000, or 16000 */
	uint32_t clamshell_mode;
	/* 1 = Clamshell mode, 0 = Non-clamshell mode */
	uint32_t feature_bits;
	/* See feature_bit_u for possible values. */
	uint32_t board_type;
	/* See board_type_e for possible values. */
	uint32_t mrisc_fw_version_major;
	/* To be incremented if FW major version changes */
	uint32_t mrisc_fw_version_minor;
	/* To be incremented if FW minor version changes */
	uint32_t controller_id;
	/* ID to uniquely identify each controller (0-7) */
} gddr_params_table_t;

#endif
