/*
 * Copyright (c) 2025 Tenstorrent AI ULC
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_DT_BINDINGS_CLOCK_CONTROL_TT_BH_H
#define ZEPHYR_DT_BINDINGS_CLOCK_CONTROL_TT_BH_H

#define CLOCK_CONTROL_TT_BH_CLOCK_AICLK      0
#define CLOCK_CONTROL_TT_BH_CLOCK_ARCCLK     1
#define CLOCK_CONTROL_TT_BH_CLOCK_AXICLK     2
#define CLOCK_CONTROL_TT_BH_CLOCK_APBCLK     3
#define CLOCK_CONTROL_TT_BH_CLOCK_L2CPUCLK_0 4
#define CLOCK_CONTROL_TT_BH_CLOCK_L2CPUCLK_1 5
#define CLOCK_CONTROL_TT_BH_CLOCK_L2CPUCLK_2 6
#define CLOCK_CONTROL_TT_BH_CLOCK_L2CPUCLK_3 7
#define CLOCK_CONTROL_TT_BH_CLOCK_GDDRMEMCLK 8
#define CLOCK_CONTROL_TT_BH_INIT_STATE       9

#define CLOCK_CONTROL_TT_BH_GDDR_SPEED_TO_MEMCLK_RATIO 16

#endif /* ZEPHYR_DT_BINDINGS_CLOCK_CONTROL_TT_BH_H */
