name: Build tt-native

on:
  push:
    branches:
      - main
      - v*-branch
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - v*-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build-tt-tooling:
    runs-on: ubuntu-22.04
    name: Build tt-tooling
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run the script
        run: |
          make -j$(nproc) -C scripts/tooling OUTDIR=$PWD
      - name: Upload tt-tooling artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tt-tooling
          path: |
            tt-console
            tt-tracing
