name: Build Check

on:
  push:
    branches:
      - main
      - v*-branch
      - collab*
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - v*-branch
      - collab*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  genboards:
    runs-on: ubuntu-24.04
    outputs:
      boards: ${{ steps.genboards.outputs.boards }}
    steps:
      - uses: actions/checkout@v4
      - id: genboards
        shell: bash
        run: |
          BOARDS="$(jq -c '[.[] | .board]' .github/ci_boards.json)"
          echo "boards=$BOARDS" | tee -a $GITHUB_OUTPUT

  smc-build-only-tests:
    runs-on: ubuntu-24.04
    needs: genboards
    strategy:
      fail-fast: false
      matrix:
        board: ${{ fromJson(needs.genboards.outputs.boards) }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: tt-zephyr-platforms

      - uses: ./tt-zephyr-platforms/.github/workflows/prepare-zephyr
        with:
          app-path: tt-zephyr-platforms

      - name: Generate BOARD
        working-directory: tt-zephyr-platforms
        shell: bash
        run: |
          BOARD="$(./scripts/rev2board.sh "${{ matrix.board }}" smc)"
          echo "BOARD=$BOARD" | tee "$GITHUB_ENV"

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          docker-images: false

      - name: Build SMC Build Only Tests
        shell: bash
        run: |
          ./zephyr/scripts/twister \
            -p $BOARD \
            --build-only \
            -T tt-zephyr-platforms/app/smc \
            --outdir twister-smc-tests-${{ matrix.board }} \
            --runtime-artifact-cleanup pass \
            -j 2

      - name: Upload Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: build-smc-tests-${{ matrix.board }}
          include-hidden-files: true
          path: |
            twister-smc-tests-${{ matrix.board }}/**/handler.log
            twister-smc-tests-${{ matrix.board }}/**/twister_harness.log
            twister-smc-tests-${{ matrix.board }}/**/zephyr.dts
            twister-smc-tests-${{ matrix.board }}/**/.config
            twister-smc-tests-${{ matrix.board }}/**/*.map
            twister-smc-tests-${{ matrix.board }}/**/zephyr.elf
            twister-smc-tests-${{ matrix.board }}/**/*.lst
            twister-smc-tests-${{ matrix.board }}/twister.log
            twister-smc-tests-${{ matrix.board }}/twister.json
