name: Copyright Check

on:
  push:
    branches:
      - main
      - v*-branch
      - collab*
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - v*-branch
      - collab*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  copyright_check_job:
    runs-on: ubuntu-22.04
    name: Copyright Check
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run the script
        run: |
          ./scripts/check-copyright.py
