# Copyright (c) 2024, Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

name: Documentation

on:
  push:
    branches: [main]
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  DOXYGEN_VERSION: 1.14.0

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: tt-zephyr-platforms

      - name: Install dependencies
        working-directory: tt-zephyr-platforms
        run: |
          wget --no-verbose "https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VERSION//./_}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz"
          tar xf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
          echo "${PWD}/doxygen-${DOXYGEN_VERSION}/bin" >> $GITHUB_PATH
          pip install -r doc/requirements.txt

      - name: Clone Zephyr
        run: |
          pip install west
          west init -l tt-zephyr-platforms
          west update
          west patch apply

      - name: Build
        working-directory: tt-zephyr-platforms
        run: |
          cd doc

          # IMPORTANT: symlink directories here that are needed during the sphinx build
          # There may be a better way to do this, but this seems to be simplest at the moment.
          # It's required because symlinks trip check_compliance.py.
          ln -sf ../boards .

          rm -f zephyr.tag
          wget https://docs.zephyrproject.org/latest/doxygen/html/zephyr.tag -O /tmp/zephyr.tag

          # We should try to limit the number of environment variables we reference in Doxyfile
          # but they can be added here, as needed.
          # For reference, this method of passing variables is based on Doxygen's examples
          # https://github.com/doxygen/doxygen/issues/7975
          ( \
            cat Doxyfile; \
            echo "PROJECT_NUMBER=$(../scripts/get_ttzp_version.py)"; \
            echo "" \
          ) | doxygen -

          make html

          mkdir deploy
          mv _build_doxygen/html deploy/doxygen
          mv _build_sphinx/html/* deploy
          rm -rf _build_doxygen _build_sphinx

      - name: Setup pages
        if: github.event_name != 'pull_request'
        uses: actions/configure-pages@v4

      - name: Upload pages artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v3
        with:
          path: tt-zephyr-platforms/doc/deploy

      - name: Upload artifacts
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          path: tt-zephyr-platforms/doc/deploy

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    if: github.event_name != 'pull_request'
    permissions:
      pages: write
      id-token: write
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
