name: Zephyr Environment Setup (Composite)
description: |
  This workflow prepares the Zephyr environment for building, testing, or other tasks. It is
  intended to be used as a reusable (composite) step in other workflows.

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    # TODO: potentially improve caching strategy
    # Note: this step performs "west init", "west update", and installs zephyr python dependencies
    - name: Set up Zephyr project
      uses: zephyrproject-rtos/action-zephyr-setup@v1
      with:
        app-path: .
        toolchains: arm-zephyr-eabi:riscv64-zephyr-elf:x86_64-zephyr-elf:arc-zephyr-elf

    - name: Install additional python dependencies
      shell: bash
      run: |
        pip install -r scripts/requirements.txt

    - name: Verify binary blobs
      shell: bash
      run: |
        west blobs fetch

    - name: Apply patches
      shell: bash
      run: |
        west -v patch apply
