name: Zephyr Environment Setup (Composite)
description: |
  This workflow prepares the Zephyr environment for building, testing, or other tasks. It is
  intended to be used as a reusable (composite) step in other workflows.

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Set up Zephyr project
      uses: zephyrproject-rtos/action-zephyr-setup@v1
      with:
        app-path: .
        toolchains: arm-zephyr-eabi:riscv64-zephyr-elf:x86_64-zephyr-elf:arc-zephyr-elf

    - name: Install additional python dependencies
      shell: bash
      run: |
        pip install -r scripts/requirements.txt

    - id: gen-west-workspace
      shell: bash
      run: |
        WEST_WORKSPACE="$(realpath $PWD/..)"
        echo "west-workspace=$WEST_WORKSPACE" > "$GITHUB_OUTPUT"
        WEST_WORKSPACE_HASH="$(echo "$WEST_WORKSPACE" | sha256sum | cut -d' ' -f1)"
        echo "west-workspace-hash=$WEST_WORKSPACE_HASH" > "$GITHUB_OUTPUT"

    - name: Verify binary blobs
      shell: bash
      run: |
        west blobs fetch

    - name: Apply patches
      shell: bash
      run: |
        west -v patch apply
